# GitHub Sponsors Configuration
# Uncomment and add your sponsorship details if applicable

# github: yourusername
# patreon: yourusername
# ko_fi: yourusername
# custom: ["https://your-donation-link.com"]
